import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// Gọi Sidebar trước tiên
import Sidebar from "../components/Sidebar";
import Header from "../components/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#121212]`}
    >
      <body className="flex h-screen overflow-hidden">
        {/* Sidebar nằm bên trái */}
        <Sidebar />

        {/* Phần nội dung chính */}
        <div className="flex flex-col flex-1 overflow-auto bg-white text-black">
          {/* Header nằm trong nội dung */}
          <Header />

          {/* Nội dung trang */}
          <main className="flex-1 px-6 py-6 max-w-7xl mx-auto w-full">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}